---
title: "eda_new"
author: "KANG CHAEREE"
date: '2022 5 10 '
output: word_document
---

#Load Data
```{r}
library(readxl)
library(dplyr)
dat<-read.csv('C:/Users/cny13/OneDrive/바탕 화면/데마/프로젝트/weather.csv')
dat$일시<-as.POSIXct(dat$일시)
new<-dat%>%filter(지점명==c('서울','인천','대전','대구','울산','광주','부산','대구(기)'))
new<-new[,c(2,3,4,19:35)]

seo<-new%>%filter(지점명=='서울')
inc<-new%>%filter(지점명=='인천')
daj<-new%>%filter(지점명=='대전')
dag<-new%>%filter(지점명=='대구')
uls<-new%>%filter(지점명=='울산')
gwa<-new%>%filter(지점명=='광주')
bus<-new%>%filter(지점명=='부산')
dagg<-new%>%filter(지점명=='대구(기)')

```
#기상관측 시각
```{r}
#서울, 대구(기) 기상관측 시각: 1일 3회(2, 10, 18시)
seo[1:30,c(2,3,6)]
dagg[1:30,c(2,3,6)]

#인천, 대전 기상관측 시각: 1일 3회(3, 11, 19시)
inc[1:30,c(2,3,6)]
daj[1:30,c(2,3,6)]

#대구 기상관측 시각: 1일 3회(4, 12, 20시)
dag[1:30,c(2,3,6)]

#울산 기상관측 시각: 1일 3회(5, 13, 21시)
uls[1:30,c(2,3,6)]

#광주 기상관측 시각: 1일 3회(0, 8, 16시)
gwa[1:30,c(2,3,6)]

#부산 기상관측 시각: 1일 3회(1, 9, 17시)
bus[1:30,c(2,3,6)]

```



#해면기압 EDA
```{r}
#해면기압: 평균 해수면(해발고도 0m)을 기준 고도(reference level)로 하여 관측소에서 관측한 기압을 관측소의 해발고도에 대해 보정한 기압
#여름에 낮고 겨울에 높은 추세가 보인다.


plot(seo[,4],main='서울 해면기압');plot(inc[,4],main='인천 해면기압');plot(daj[,4],main='대전 해면기압');plot(dag[,4],main='대구 해면기압');plot(uls[,4],main='울산 해면기압');plot(gwa[,4],main='광주 해면기압');plot(bus[,4],main='부산 해면기압');plot(dagg[,4],main='대구(기) 해면기압')
```


#일조.hr EDA
```{r}
#일조시간: 태양광선이 구름이나 안개 등에 의해서 차단되지 않고 지표면을 비춘 시간(단위: 시간)
#정오즈음에 일조시간이 가장 길다. 구름과 안개에 영향을 받는다.
#1에 근접할수록 날씨가 맑다는 뜻. 
#NA가 너무 많다. 하루에 3번 측정하니까 NA는 같은 시간대 앞뒤 날짜 평균으로...? 방법 생각 필요...
head(seo[,c(3,6,7)])
seo[1:30,c(3,6)]

plot(seo[,6],main='서울 일조');plot(inc[,6],main='인천 일조');plot(daj[,6],main='대전 일조');plot(dag[,6],main='대구 일조');plot(uls[,6],main='울산 일조');plot(gwa[,6],main='광주 일조');plot(bus[,6],main='부산 일조');plot(dagg[,6],main='대구(기) 일조')
```

#일사.MJ.m2 EDA
```{r}
#일사: 지표면에 도달한 태양복사에너지. 하루 중에는 남중시에 최대, 1년 중에는 하지에 최대.

plot(seo[,8],main='서울 일사');plot(inc[,8],main='인천 일사');plot(daj[,8],main='대전 일사');plot(dag[,8],main='대구 일사');plot(uls[,8],main='울산 일사');plot(gwa[,8],main='광주 일사');plot(bus[,8],main='부산 일사');plot(dagg[,8],main='대구(기) 일사')
```


#적설 EDA
```{r}
#적설: 지면에 쌓인 눈. X시간 신적설은 X시간마다 측정. 
#겨울(11~2월) 제외하고는 NA-> 0으로 처리.
dim(seo);sum(is.na(seo$적설.cm.))
snow<-na.omit(seo[,c(3,10)])
snow
```


```{r}
#각 세로로 구분된 건 15~18년 연도별
#울산, 부산은 적설 데이터 아예 없음.

plot(seo[,10],main='서울 적설');plot(inc[,10],main='인천 적설');plot(daj[,10],main='대전 적설');plot(dag[,10],main='대구 적설');plot(gwa[,10],main='광주 적설');plot(dagg[,10],main='대구(기) 적설')

#plot(uls[,10],main='울산 적설');plot(bus[,10],main='부산 적설')
```



##1년 내 적설 보기
```{r}
plot(snow[c(29:82),1],snow[c(29:82),2],main='17 서울 적설');plot(snow[c(29:60),1],snow[c(29:60),2],main='17.1~2월 서울 적설')

```



#X3시간신적설 EDA
```{r}
#X시간 신적설: X시간 동안 쌓인 눈
#NA는 0으로 처리.

plot(seo[,11],main='서울 X3시간 신적설');plot(inc[,11],main='인천 X3시간 신적설');plot(daj[,11],main='대전 X3시간 신적설');plot(dag[,11],main='대구 X3시간 신적설');plot(gwa[,11],main='광주 X3시간 신적설');plot(dagg[,11],main='대구(기) X3시간 신적설')
```

##1년 내 3시간 신적설 보기
```{r}
#데이터가 연도별로 가장 많은게 5개여서 패턴 확인하기에는 무리.
nsnow<-seo%>%filter(X3시간신적설.cm.!='NA')
plot(nsnow[,3],nsnow[,11],main='서울 신적설');plot(nsnow[c(5:11),3],nsnow[c(5:11),11],main='17년 1~12월 서울 신적설')
```


#전운량.10분위 EDA
```{r}
#전운량: 구름의 양. 구름이 하늘을 완전히 덮으면 10 아니면 0.
#맑음: 2.4이하, 구름조금: 2.5~5.4, 구름많음: 5.5~8.4, 흐림:8.5~(종합기후변화감시정보).
#대구는 15년 6월 이후부터 데이터 있음. 이전은 다 NA.

plot(seo[,12],main='서울 전운량.10분위');plot(inc[,12],main='인천 전운량.10분위');plot(daj[,12],main='대전 전운량.10분위');plot(dag[,12],main='대구 전운량.10분위');plot(gwa[,12],main='광주 전운량.10분위');plot(dagg[,12],main='대구(기) 전운량.10분위')
```
##1년 단위로 보기
```{r}
#겨울철이 맑고 여름철이 흐리다. 겨울철에 0에 점들이 진하게 찍혀있고 여름엔 그 반대이다.
plot(seo[1:1095,3,],seo[1:1095,12],main='서울 15년 전운량')
```



#중하층운량.10분위 EDA
```{r}
#중하층운량: 중층과 하층에 있는 구름이 덮은 양. 두께를 의미하는게 아님. 
#0이면 구름이 전혀 없음. 10이면 하늘에 구름이 꽉 차있는 상태. 밤에는 별이 보이지 않으면 구름이 덮인 것으로 간주.
#중하층운은 비랑 주로 관련이 있으나 맑은 날에 보이는 구름도 있음.



plot(seo[,13],main='서울 중하층운량.10분위');plot(inc[,13],main='인천 중하층운량.10분위');plot(daj[,13],main='대전 중하층운량.10분위');plot(dag[,13],main='대구 중하층운량.10분위');plot(gwa[,13],main='광주 중하층운량.10분위');plot(dagg[,13],main='대구(기) 중하층운량.10분위')
```

##서울 연도별 보기:(18년 제외) 여름에 맑은 날이 적다.
```{r}
plot(seo[1:1095,3],seo[1:1095,13], main='서울 15년 중하층운량');plot(seo[1096:2193 ,3],seo[1096:2193,13], main='서울 16년 중하층운량');plot(seo[2194:3288 ,3],seo[2194:3288,13], main='서울 17년 중하층운량');plot(seo[3289:4383 ,3],seo[3289:4383,13], main='서울 18년 중하층운량')
```


##서울 연도별 보기:15,17은 여름에 맑은 날이 적다.
```{r}
plot(inc[1:1095,3],inc[1:1095,13], main='인천 15년 중하층운량');plot(inc[1096:2193 ,3],inc[1096:2193,13], main='인천 16년 중하층운량');plot(inc[2194:3288 ,3],inc[2194:3288,13], main='인천 17년 중하층운량');plot(inc[3289:4383 ,3],inc[3289:4383,13], main='인천 18년 중하층운량')
```





#운형.운형약어 EDA
```{r}
#운형약어: 구름 형태. 10가지(권운 Ci, 권적운 Cc, 권층운 Cs, 고적운 Ac, 고층운 As, 난층운 Ns, 층적운 Sc, 층운 St, 적운 Cu, 적란운 Cb)인데 데이터에는 여러개 연결되서 있음.

#Ci, Cu: 맑은 날씨
#Cc, Cs: 안 좋은 날씨
#Cs, Ns, Cb: 비나 눈
#Sc: 우적, 싸락눈, 빙정, 눈 조각
#St: 안개 낀 모습, 안개비, 가루눈

#계절별로 구분되지는 않지만 주로 봄: Ci, Cs/ 여름: Cu, Cb
barplot(seo[,14])

```


#최저운고.100m EDA
```{r}
#운고: 구름의 높이
#왜 16년 10월 이전엔 듬성듬성일까...?

plot(seo[,15],main='서울 최저운고.100m');plot(inc[,15],main='인천 최저운고.100m');plot(daj[,15],main='대전 최저운고.100m');plot(dag[,15],main='대구 최저운고.100m');plot(gwa[,15],main='광주 최저운고.100m');plot(dagg[,15],main='대구(기) 최저운고.100m')
```


```{r}
#NA 제거하고 그려도 비슷한 패턴
cloud<-na.omit(seo[,15])
plot(cloud)
```



#시정.10m EDA
```{r}
#시정: 대기를 통해 어느 정도의 전망이 가능한가 측정.
#대부분 2000 이하. 
#대구는 15년 1~3월이 다 NA.
plot(seo[,16],main='서울 시정');plot(inc[,16],main='인천 시정');plot(daj[,16],main='대전 시정');plot(dag[,16],main='대구 시정');plot(gwa[,16],main='광주 시정');plot(dagg[,16],main='대구(기) 시정')
```


#지면상태.지면상태코드 EDA
```{r}
#지면상태코드: 물이나 눈이 덮여 있는지. 1~19
#16.7.1 이후 관측 종료되서 이후 데이터는 NA
#광주, 대구(기)는 전체 NA

plot(seo[,17],main='서울 지면상태.지면상태코드');plot(inc[,17],main='인천 지면상태.지면상태코드');plot(daj[,17],main='대전 지면상태.지면상태코드');plot(dag[,17],main='대구 지면상태.지면상태코드');plot(gwa[,17],main='광주 지면상태.지면상태코드');plot(dagg[,17],main='대구(기) 지면상태.지면상태코드')
```


#현상번호.국내식 EDA
```{r}
#현상번호: 날씨 특징 담은 번호. 01~143, A0~A10 있음.데이터에는 8자리도 있는데 여러개가 합쳐진 듯...

plot(seo[,18],main='서울 현상번호.국내식');plot(inc[,18],main='인천 현상번호.국내식');plot(daj[,18],main='대전 현상번호.국내식');plot(dag[,18],main='대구 현상번호.국내식');plot(gwa[,18],main='광주 현상번호.국내식');plot(dagg[,18],main='대구(기) 현상번호.국내식')

```


#지면온도 EDA
```{r}
#겨울에 낮고 여름에 높다. 
#추세 따라 NA 처리

plot(seo[,19],main='서울 현상번호.국내식');plot(inc[,19],main='인천 현상번호.국내식');plot(daj[,19],main='대전 현상번호.국내식');plot(dag[,19],main='대구 현상번호.국내식');plot(gwa[,19],main='광주 현상번호.국내식');plot(dagg[,19],main='대구(기) 현상번호.국내식')
```





